"""lauren-mcp — Model Context Protocol server and client for Lauren applications."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from ._bridge import McpServerConfig, McpToolBridge
from ._client._factory import McpServer
from ._client._protocol import McpClientProtocol
from ._client._stdio import McpCallError
from ._mcp_version import LATEST, STABLE, SUPPORTED
from ._server._context import McpToolContext
from ._server._dispatcher import McpForbiddenError
from ._server._exec_context import McpExecutionContext
from ._types import (
    AnyContent,
    AudioContent,
    BlobResource,
    ClientCapabilities,
    CompletionResult,
    CreateMessageParams,
    CreateMessageResult,
    ElicitResult,
    EmbeddedResource,
    GetPromptParams,
    GetPromptResult,
    ImageContent,
    Implementation,
    InitializeParams,
    InitializeResult,
    JsonRpcError,
    JsonRpcErrorResponse,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    McpElicitationNotAvailable,
    McpErrorCode,
    McpParseError,
    McpSamplingNotAvailable,
    McpUrlElicitationNotAvailable,
    PromptArgument,
    PromptMessage,
    PromptSchema,
    ReadResourceParams,
    ReadResourceResult,
    ResourceAnnotations,
    ResourceContent,
    ResourceLink,
    ResourceResult,
    ResourceSchema,
    Role,
    Root,
    SamplingMessage,
    ServerCapabilities,
    TextContent,
    ToolAnnotations,
    ToolCallParams,
    ToolOutput,
    ToolResult,
    ToolResultContent,
    ToolSchema,
    ToolStream,
    ToolUseContent,
    UrlElicitResult,
    build_error_response,
    parse_message,
    validate_sampling_messages,
)
from .server import (
    LaurenMcpMemoryServer,
    McpServerModule,
    McpToolNameCollision,
    RouteEntry,
    build_openapi_server_class,
    mcp_lifespan,
    mcp_prompt,
    mcp_resource,
    mcp_server,
    mcp_tool,
)
from .server._handlers import McpCallHandler

__all__ = [
    "mcp_server",
    "mcp_tool",
    "mcp_resource",
    "mcp_prompt",
    "mcp_lifespan",
    "McpServerModule",
    "McpServer",
    "McpClientProtocol",
    "McpCallError",
    "McpServerConfig",
    "McpToolBridge",
    "McpToolContext",
    "McpExecutionContext",
    "McpForbiddenError",
    "McpCallHandler",
    "McpToolNameCollision",
    "RouteEntry",
    "build_openapi_server_class",
    "JsonRpcRequest",
    "JsonRpcNotification",
    "JsonRpcResponse",
    "JsonRpcError",
    "JsonRpcErrorResponse",
    "McpErrorCode",
    "McpParseError",
    "ClientCapabilities",
    "ServerCapabilities",
    "Implementation",
    "InitializeParams",
    "InitializeResult",
    "TextContent",
    "ImageContent",
    "EmbeddedResource",
    "AnyContent",
    "ToolAnnotations",
    "ToolSchema",
    "ToolCallParams",
    "ToolResult",
    "ToolOutput",
    "ToolStream",
    "ResourceSchema",
    "ResourceContent",
    "ReadResourceParams",
    "ReadResourceResult",
    "BlobResource",
    "ResourceResult",
    "PromptArgument",
    "PromptSchema",
    "PromptMessage",
    "GetPromptParams",
    "GetPromptResult",
    "SamplingMessage",
    "CreateMessageParams",
    "CreateMessageResult",
    "McpSamplingNotAvailable",
    "ElicitResult",
    "McpElicitationNotAvailable",
    "Root",
    "parse_message",
    "build_error_response",
    "LATEST",
    "STABLE",
    "SUPPORTED",
    # New wire types
    "AudioContent",
    "ResourceLink",
    "ToolUseContent",
    "ToolResultContent",
    "ResourceAnnotations",
    "Role",
    "UrlElicitResult",
    "McpUrlElicitationNotAvailable",
    "CompletionResult",
    "validate_sampling_messages",
    # Memory server
    "LaurenMcpMemoryServer",
]

try:
    __version__: str = version("lauren-mcp")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"
